name: 🌟 Wünsche & Vorschläge
description: Schlage eine Idee für unser Projekt vor.
labels: [request]
body:
  - type: markdown
    attributes:
      value: |
        # Über deinen Vorschlag
  - type: dropdown
    id: type
    validations:
      required: true
    attributes:
      label: Was möchtest du vorschlagen?
      description: Um welche Art Vorschlag handelt es sich?
      multiple: false
      options:
        - Ein neues Feature
        - Eine Verbesserung
        - Eine Ergänzung
        - Etwas Anderes
  - type: textarea
    id: suggestion
    attributes:
      label: Beschreibe deinen Vorschlag
      description: |
        Bezieht sich deine Anfrage auf ein Problem? Bitte beschreibe es.
        Du kannst hier zusätzlich noch Screenshots/Bildaufnahmen anhängen.
      placeholder: Eine klare und prägnante Beschribung über das Problem. z.B. Es frustriert mich immer wenn [...]
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: Wie können wir den Bug reproduzieren?
      description: |
        Zeige uns Schritt für Schritt, wie wir diesen Bug nachstellen können.
        Es wäre auch hier sehr hilfreich, wenn du zusätzlich noch Screenshots/Bildaufnahmen hier anhängen könntest.
      placeholder: |
        1. Gehe zu '...'
        2. Drücke '....'
        3. Suche nach '....'
        4. Siehe Fehler
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        # Anderes
  - type: textarea
    id: more
    attributes:
      label: Weitere Informationen
      description: Füge hier alle weiteren Informationen hinzu, die mit dem Problem zu tun haben.
      placeholder: |
        Weitere relevante Informationen kannst du uns hier mitteilen!
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Kontakt-Informationen (Öffentlich)
      description: Wie können wir dich erreichen, wenn wir weitere Informationen benötigen?
      placeholder: mail@example.com
    validations:
      required: false
